#!/usr/bin/env python3
"""shomescale client DNS setup - dnsmasq forwarding for *.shomescale

Configures a local dnsmasq that:
- Forwards *.shomescale queries to the directory server DNS (port 53)
- Forwards all other queries to upstream gateway
- Backs up and restores /etc/resolv.conf
"""

import logging
import os
import subprocess
import time

logger = logging.getLogger("shomescale-dns")

DNSMASQ_CONF = "/etc/dnsmasq.d/shomescale.conf"
DNSMASQ_PID = "/var/run/shomescale-dnsmasq.pid"
RESOLV_CONF = "/etc/resolv.conf"
RESOLV_CONF_BACKUP = "/etc/resolv.conf.shomescale.bak"

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def setup_dns(server_ip, server_dns_port=53):
    """Configure dnsmasq to forward *.shomescale to the directory server DNS."""
    global _upstream_ns
    ensure_dnsmasq()

    # Read current resolv.conf to find upstream nameservers
    _read_resolv_conf()
    if not _upstream_ns:
        _upstream_ns = ["192.168.35.1"]

    # Backup original resolv.conf if not already backed up
    if not os.path.exists(RESOLV_CONF_BACKUP):
        _write_backup()
        logger.info("Backed up %s to %s", RESOLV_CONF, RESOLV_CONF_BACKUP)

    # Write dnsmasq config
    _write_dnsmasq_conf(server_ip, server_dns_port)

    # Update /etc/resolv.conf to point to localhost first
    _write_resolv_conf()

    # Restart dnsmasq
    dnsmasq_restart()
    time.sleep(1)
    logger.info("DNS setup complete. *.shomescale -> %s (port %d)", server_ip, server_dns_port)


def clean_dns():
    """Remove dnsmasq config, restore original resolv.conf, restart dnsmasq."""
    if os.path.exists(RESOLV_CONF_BACKUP):
        _restore_backup()
        logger.info("Restored %s from backup", RESOLV_CONF)

    if os.path.exists(DNSMASQ_CONF):
        os.remove(DNSMASQ_CONF)
        logger.info("Removed dnsmasq config %s", DNSMASQ_CONF)

    dnsmasq_restart()
    logger.info("DNS cleanup complete")


# ---------------------------------------------------------------------------
# Internal state
# ---------------------------------------------------------------------------

_upstream_ns = []
_search_domains = []


def _read_resolv_conf():
    """Parse /etc/resolv.conf to extract upstream nameservers."""
    global _upstream_ns, _search_domains
    _upstream_ns = []
    _search_domains = []
    try:
        with open(RESOLV_CONF) as f:
            original = f.read()
        for line in original.splitlines():
            parts = line.strip().split()
            if len(parts) >= 2 and parts[0] == "nameserver":
                _upstream_ns.append(parts[1])
            if parts and parts[0] == "search":
                _search_domains.extend(parts[1:])
    except FileNotFoundError:
        pass


def _write_backup():
    try:
        with open(RESOLV_CONF) as f:
            content = f.read()
        with open(RESOLV_CONF_BACKUP, "w") as f:
            f.write(content)
    except Exception:
        pass


def _restore_backup():
    with open(RESOLV_CONF_BACKUP) as f:
        original = f.read()
    with open(RESOLV_CONF, "w") as f:
        f.write(original)
    os.remove(RESOLV_CONF_BACKUP)


def _write_dnsmasq_conf(server_ip, server_dns_port):
    """Write dnsmasq config file that forwards *.shomescale to server DNS."""
    os.makedirs(os.path.dirname(DNSMASQ_CONF), exist_ok=True)
    upstream_lines = "\n".join(f"server={ns}" for ns in _upstream_ns)
    content = f"""
# shomescale DNS forwarding config
# Generated by shomescale client - DO NOT EDIT
listen-address=127.0.0.1
no-resolv
# Forward all queries to the gateway/upstream nameservers
{upstream_lines}
# Forward ONLY *.shomescale queries to the directory server DNS
server=/shomescale/{server_ip}#{server_dns_port}
expand-hosts
"""
    with open(DNSMASQ_CONF, "w") as f:
        f.write(content)
    logger.info("Wrote dnsmasq config to %s", DNSMASQ_CONF)


def _write_resolv_conf():
    """Update /etc/resolv.conf: point to localhost first, then upstream."""
    content = "# Managed by shomescale client\nnameserver 127.0.0.1\n"
    for ns in _upstream_ns:
        content += f"nameserver {ns}\n"
    if _search_domains and "shomescale" not in _search_domains:
        _search_domains.append("shomescale")
    content += f"search {' '.join(_search_domains)}\n"
    with open(RESOLV_CONF, "w") as f:
        f.write(content)
    logger.info("Updated %s to use dnsmasq (127.0.0.1)", RESOLV_CONF)


# ---------------------------------------------------------------------------
# dnsmasq management
# ---------------------------------------------------------------------------

def dnsmasq_restart():
    """Stop and start dnsmasq with explicit config file."""
    try:
        subprocess.check_call(["pkill", "dnsmasq"])
        time.sleep(0.5)
    except subprocess.CalledProcessError:
        pass
    try:
        subprocess.check_call([
            "dnsmasq",
            "-C", DNSMASQ_CONF,
            "-x", DNSMASQ_PID,
        ])
        logger.info("dnsmasq started with config %s", DNSMASQ_CONF)
    except subprocess.CalledProcessError as e:
        logger.error("Failed to start dnsmasq: %s", e)
        raise


# ---------------------------------------------------------------------------
# dnsmasq install check
# ---------------------------------------------------------------------------

def ensure_dnsmasq():
    """Install dnsmasq if not already present."""
    try:
        subprocess.check_call(
            ["dnsmasq", "--version"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    logger.info("dnsmasq not found. Installing...")
    info = {}
    if os.path.exists("/etc/os-release"):
        with open("/etc/os-release") as f:
            for line in f:
                k, _, v = line.partition("=")
                if v:
                    info[k] = v.strip('"')
    distro_id = info.get("ID", "").lower()
    id_like = info.get("ID_LIKE", "").lower()

    if distro_id in ("ubuntu", "debian") or "debian" in id_like:
        subprocess.check_call(["apt-get", "update"], stdout=subprocess.DEVNULL)
        subprocess.check_call(["apt-get", "install", "-y", "dnsmasq"])
    elif distro_id in ("rhel", "rocky", "centos", "almalinux", "redhat") or "rhel" in id_like:
        subprocess.check_call(["dnf", "install", "-y", "dnsmasq"])
    else:
        logger.error("Unsupported distro. Install dnsmasq manually.")
        import sys; sys.exit(1)
