[Interface]
Address = 100.64.0.1/24
PrivateKey = oAaQ30mYMH0iRJMOQ11CfByhcdvE34yvJd4w3bHLFHY=
ListenPort = 51820

[Peer]
PublicKey = vYki5syzkBv7rdkUOwsRQCRDzUL+wc6nDBvEPO8Bkkk=
AllowedIPs = 100.64.0.2/32
Endpoint = 192.168.35.211:51820
PersistentKeepalive = 25

[Peer]
PublicKey = kUP1cM/0uGa5baqbYMVYzX3XjqkXgPznhHDmDpxyoxY=
AllowedIPs = 100.64.0.3/32
Endpoint = 192.168.35.212:51820
PersistentKeepalive = 25

[Peer]
PublicKey = PG27meUVtlSgpOR+huMDOSgKQYY3bSiiJ1Ri+ONABFM=
AllowedIPs = 100.64.0.4/32
Endpoint = 192.168.35.213:51820
PersistentKeepalive = 25
